name: 5E Character Sheet Builder CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test the App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      
      - name: Install yarn
        run: npm i -g yarn
      
      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
  lint:
    name: Lint the App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      
      - name: Install yarn
        run: npm i -g yarn
      
      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint